#!/bin/sh -ex

# Boiler plate code to print context of this script
juju-log $JUJU_REMOTE_UNIT modified its settings
juju-log Relation settings:
relation-get
juju-log Relation members:
relation-list

. inc/common
: <<EOF

# If there is a config file already, Joomla is already installed & config'ed
if [ -f "$config_file_path" ]; then
	# TODO: Update the config file with new DB values even 
	#       if joomla is alredy installed
	juju-log "Joomla is already setup, just silently going away"
	exit 0
fi
EOF

# Relation properties
database=`relation-get database`
user=`relation-get user`
password=`relation-get password`
host=`relation-get private-address`

# Secret key for configuring Joomla
secret_key=`pwgen 32 1`

# Sanity checks
## If there is no database name defined, die
if [ -z "$database" ] ; then
    exit 0
fi

juju-log Config
sed -i "s|public \$host = '.*';|public \$host = '"$host"';|g" $config_file_path
sed -i "s|public \$user = '.*';|public \$user = '"$user"';|g" $config_file_path
sed -i "s|public \$password = '.*';|public \$password = '"$password"';|g" $config_file_path
sed -i "s|public \$db = '.*';|public \$db = '"$database"';|g" $config_file_path
sed -i "s|public \$dbprefix = '.*';|public \$dbprefix = 'jos_';|g" $config_file_path
sed -i "s|public \$secret = '.*';|public \$secret = '"$$secret_key"';|g" $config_file_path

# least access permissions for the configuration file
chown www-data:www-data $config_file_path
chmod 0640 $config_file_path

juju-log "Opening port 80"
open-port 80/tcp
open-port 443/tcp
