#!/bin/sh -ex

. inc/common

juju-log "Installing software"

apt-get update
apt-get -y install apache2 php5-gd libapache2-mod-php5 mysql-client-core-5.5 php5-mysql pwgen

a2enmod php5 headers
service apache2 restart

juju-log "Download"
JOOMLA_TARBALL="https://github.com/joomla/joomla-cms/releases/download/3.3.6/Joomla_3.3.6-Stable-Full_Package.tar.gz"
JOOMLA_MD5SUM="a783a14939afaaf33040a1decffccbae"
curl -vv -L $JOOMLA_TARBALL > /tmp/joomla.tar.gz

juju-log "Extract"
mkdir -p $install_path
tar -C $install_path -zxf /tmp/joomla.tar.gz
rm -f /tmp/joomla.tar.gz
mv $install_path/htaccess.txt $install_path/.htaccess
#cp $install_path/installation/configuration.php-dist $install_path/configuration.php

(
cd $install_path
patch -p1 files/default_database.patch
)

# Secret key for configuring Joomla
secret_key=`pwgen 32 1`
sed -i "s|public \$secret = '.*';|public \$secret = '"$secret_key"';|g" $install_path/installation/configuration.php-dist

# Set better file permissions
set_permissions
